
export const CAR_PIECES = [
  { id: 'pd', label: 'Para-choque Dianteiro' },
  { id: 'pt', label: 'Para-choque Traseiro' },
  { id: 'capo', label: 'Capô' },
  { id: 'teto', label: 'Teto' },
  { id: 'tampa_tras', label: 'Tampa Traseira / Porta-Malas' },
  { id: 'pde', label: 'Para-lama Dianteiro Esquerdo' },
  { id: 'pdd', label: 'Para-lama Dianteiro Direito' },
  { id: 'pte', label: 'Para-lama Traseiro Esquerdo' },
  { id: 'ptd', label: 'Para-lama Traseiro Direito' },
  { id: 'pode', label: 'Porta Dianteira Esquerda' },
  { id: 'podd', label: 'Porta Dianteira Direita' },
  { id: 'pote', label: 'Porta Traseira Esquerda' },
  { id: 'potd', label: 'Porta Traseira Direita' },
  { id: 'late', label: 'Lateral Esquerda' },
  { id: 'latd', label: 'Lateral Direita' },
  { id: 'sol_e', label: 'Soleira Esquerda' },
  { id: 'sol_d', label: 'Soleira Direita' },
  { id: 'col_a_e', label: 'Coluna A Esquerda' },
  { id: 'col_a_d', label: 'Coluna A Direita' },
  { id: 'col_b_e', label: 'Coluna B Esquerda' },
  { id: 'col_b_d', label: 'Coluna B Direita' },
  { id: 'col_c_e', label: 'Coluna C Esquerda' },
  { id: 'col_c_d', label: 'Coluna C Direita' },
  { id: 'farol_e', label: 'Farol Esquerdo' },
  { id: 'farol_d', label: 'Farol Direito' },
  { id: 'lanterna_e', label: 'Lanterna Esquerda' },
  { id: 'lanterna_d', label: 'Lanterna Direito' },
  { id: 'rete', label: 'Retrovisor Esquerdo' },
  { id: 'retd', label: 'Retrovisor Direito' },
  { id: 'grade', label: 'Grade Dianteira' },
  { id: 'spoiler', label: 'Spoiler / Saia Lateral' },
];
