export const SERVICE_STATUS_LABELS = {
  em_espera: "Em Espera",
  na_oficina: "Na Oficina",
  finalizado: "Finalizado",
};

export const FUNILARIA_MATERIALS_LIST = [
  { id: "lixa_dagua_220", name: "LIXA D'ÁGUA GRÃO 220" },
  { id: "lixa_dagua_400", name: "LIXA D'ÁGUA GRÃO 400" },
  { id: "lixa_dagua_600", name: "LIXA D'ÁGUA GRÃO 600" },
  { id: "lixa_dagua_1200", name: "LIXA D'ÁGUA GRÃO 1200" },
  { id: "lixa_seca_80", name: "LIXA SECA GRÃO 80" },
  { id: "lixa_seca_150", name: "LIXA SECA GRÃO 150" },
  { id: "lixa_seca_220", name: "LIXA SECA GRÃO 220" },
  { id: "lixa_roquite_80", name: "LIXA ROQUITE GRÃO 80" },
  { id: "lixa_roquite_120", name: "LIXA ROQUITE GRÃO 120" },
  { id: "lixa_roquite_220", name: "LIXA ROQUITE GRÃO 220" },
  { id: "massa_poliester", name: "MASSA POLIÉSTER" },
  { id: "desengraxante", name: "DESENGRAXANTE" },
  { id: "diluente_universal", name: "DILUENTE UNIVERSAL" },
  { id: "thinner_limpeza", name: "THINNER DE LIMPEZA" },
  { id: "fita_crepe", name: "FITA CREPE" },
  { id: "fita_dupla_face", name: "FITA DUPLA FACE" },
  { id: "papel_isolante", name: "PAPEL ISOLANTE" },
  { id: "promotor_aderencia", name: "PROMOTOR DE ADERÊNCIA" },
  { id: "primer_pu", name: "PRIMER PU" },
  { id: "primer_multifill", name: "PRIMER MULTIFILL" },
  { id: "tinta_base", name: "TINTA BASE" },
  { id: "tinta_preto_fosco", name: "TINTA PRETO FOSCO VINÍLICO" },
  { id: "verniz_alto_solidos", name: "VERNIZ ALTO SÓLIDOS" },
  { id: "polidor_premium", name: "POLIDOR PREMIUM" },
  { id: "cera_lustradora", name: "CERA LUSTRADORA" },
  { id: "boina_polimento", name: "BOINA DE POLIMENTO" },
  { id: "boina_espuma", name: "BOINA ESPUMA" },
  { id: "estopa", name: "ESTOPA" },
];

export const MECHANIC_PIECES = [
  { id: "motor", label: "Motor" },
  { id: "cambio", label: "Câmbio" },
  { id: "susp_diant", label: "Suspensão Dianteira" },
  { id: "susp_tras", label: "Suspensão Traseira" },
  { id: "freio_diant", label: "Freio Dianteiro" },
  { id: "freio_tras", label: "Freio Traseiro" },
  { id: "injecao", label: "Injeção Eletrônica" },
  { id: "eletrica", label: "Parte Elétrica" },
  { id: "ar_cond", label: "Ar Condicionado" },
  { id: "troca_oleo", label: "Troca de Óleo / Filtros" },
  { id: "escapamento", label: "Escapamento / Silencioso" },
  { id: "arrefecimento", label: "Sistema de Arrefecimento" },
  { id: "direcao", label: "Sistema de Direção" },
  { id: "embreagem", label: "Embreagem" },
  { id: "bateria", label: "Bateria / Alternador" },
  { id: "ignicao", label: "Sistema de Ignição (Velas/Cabos)" },
  { id: "correia_dentada", label: "Correia Dentada / Tensores" },
  { id: "bomba_combustivel", label: "Bomba de Combustível" },
  { id: "pneus", label: "Pneus / Alinhamento / Balanceamento" },
  { id: "outros", label: "Outros Serviços Mecânicos" },
];

export const CAR_PIECES = [
  { id: "pd", label: "Para-choque Dianteiro" },
  { id: "pt", label: "Para-choque Traseiro" },
  { id: "capo", label: "Capô" },
  { id: "teto", label: "Teto" },
  { id: "tampa_tras", label: "Tampa Traseira / Porta-Malas" },
  { id: "pde", label: "Para-lama Dianteiro Esquerdo" },
  { id: "pdd", label: "Para-lama Dianteiro Direito" },
  { id: "pte", label: "Para-lama Traseiro Esquerdo" },
  { id: "ptd", label: "Para-lama Traseiro Direito" },
  { id: "pode", label: "Porta Dianteira Esquerda" },
  { id: "podd", label: "Porta Dianteira Direita" },
  { id: "pote", label: "Porta Traseira Esquerda" },
  { id: "potd", label: "Porta Traseira Direita" },
  { id: "late", label: "Lateral Esquerda" },
  { id: "latd", label: "Lateral Direita" },
  { id: "sol_e", label: "Soleira Esquerda" },
  { id: "sol_d", label: "Soleira Direita" },
  { id: "col_a_e", label: "Coluna A Esquerda" },
  { id: "col_a_d", label: "Coluna A Direita" },
  { id: "col_b_e", label: "Coluna B Esquerda" },
  { id: "col_b_d", label: "Coluna B Direita" },
  { id: "col_c_e", label: "Coluna C Esquerda" },
  { id: "col_c_d", label: "Coluna C Direita" },
  { id: "farol_e", label: "Farol Esquerdo" },
  { id: "farol_d", label: "Farol Direito" },
  { id: "lanterna_e", label: "Lanterna Esquerda" },
  { id: "lanterna_d", label: "Lanterna Direito" },
  { id: "rete", label: "Retrovisor Esquerdo" },
  { id: "retd", label: "Retrovisor Direito" },
  { id: "grade", label: "Grade Dianteira" },
  { id: "spoiler", label: "Spoiler / Saia Lateral" },
  { id: "capa_mot", label: "Capa do Motor (Plástico)" },
  { id: "prot_carter", label: "Protetor de Cárter" },
  { id: "vidro_dianteiro", label: "Vidro Para-brisa" },
  { id: "vidro_traseiro", label: "Vidro Traseiro" },
  { id: "caixa_roda_e", label: "Caixa de Roda Esquerda" },
  { id: "caixa_roda_d", label: "Caixa de Roda Direita" },
  { id: "painel_front", label: "Painel Frontal" },
  { id: "painel_tras", label: "Painel Traseiro" },
];
